# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='ingest',
            new_name='dataset',
        ),
    ]
