# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 08:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160307_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
    ]
