# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160215_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dataset',
            new_name='Ingest',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tree',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='dataset',
            new_name='current_ingest',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='attribute',
            name='ingest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingest'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.Tree'),
        ),
    ]
