# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160225_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Attribute')),
                ('char_value', models.CharField(max_length=256)),
            ],
            bases=('api.attribute',),
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Attribute')),
                ('float_value', models.FloatField()),
            ],
            bases=('api.attribute',),
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Attribute')),
                ('integer_value', models.IntegerField()),
            ],
            bases=('api.attribute',),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
    ]
