# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160225_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatattribute',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integerattribute',
            name='integer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
