# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160225_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FloatAttribute',
            new_name='Float',
        ),
        migrations.RenameModel(
            old_name='IntegerAttribute',
            new_name='Integer',
        ),
        migrations.RenameModel(
            old_name='CharAttribute',
            new_name='String',
        ),
        migrations.RenameField(
            model_name='string',
            old_name='char_value',
            new_name='string_value',
        ),
    ]
