# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160226_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='key',
            field=models.SlugField(max_length=256),
        ),
    ]
