# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160226_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ingest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingest')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributesets', to='api.Tree')),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='ingest',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='float',
            name='attribute_ptr',
        ),
        migrations.RemoveField(
            model_name='integer',
            name='attribute_ptr',
        ),
        migrations.RemoveField(
            model_name='string',
            name='attribute_ptr',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Float',
        ),
        migrations.DeleteModel(
            name='Integer',
        ),
        migrations.DeleteModel(
            name='String',
        ),
    ]
