# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 16:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160306_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ingest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingest')),
            ],
        ),
        migrations.RemoveField(
            model_name='attributeset',
            name='ingest',
        ),
        migrations.RemoveField(
            model_name='attributeset',
            name='tree',
        ),
        migrations.AddField(
            model_name='tree',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeSet',
        ),
        migrations.AddField(
            model_name='history',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributesets', to='api.Tree'),
        ),
    ]
